### ISSUE TITLE
 编译错误

### ISSUE THREAD

**Issue by weige502167** [segrax/xrp-vanity#1]
你能把项目，编译完成，提交吗？

**Comment by segrax** [comment]
Which operating system are you using?

**Comment by weige502167** [comment]
windows  
你支持GPU 运算  完成了吗？
如果仅支持CPU 运算 我该怎么做？需要删除或修改哪些代码？

**Comment by segrax** [comment]
This is CPU only,

GPU was planned, but it hasn't been implemented.

I will publish a release for Win x64 tonight

**Comment by weige502167** [comment]
你能添加一些功能吗？
例如：SEED前缀；snZFPBGkNYjcAUds9n........

**Comment by segrax** [comment]
That would be fairly easy to implement, but its not something people should be doing.

it would have the effect of reducing the security of your generated keys

**Comment by weige502167** [comment]
我需要它。
我有一个SEED，失去了一部分。
我不知道怎样能找回它。
如果你能帮助我，我将非常感谢。

**Comment by segrax** [comment]
Ahh i understand,

do you know how many characters are missing?  (and dont post your seed!)

**Comment by segrax** [comment]
And, do you know the address for the seed?

**Comment by weige502167** [comment]
是的，我知道。
你可以设置为seed_hex:D70E766440C58387448ED2..........
                      seed:sn6nKDAiySDfvpyN............

**Comment by weige502167** [comment]
你好，你的WIN64版本。什么时候发布？
谢谢！！

**Comment by segrax** [comment]
https://github.com/segrax/xrp-vanity/releases/tag/1.0

**Comment by weige502167** [comment]
非常感谢！！！
